# Generated by Django 2.2.17 on 2021-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unprocessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unprocessed_img', models.ImageField(blank=True, null=True, upload_to='unprocessed/')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Unprocessed',
                'verbose_name_plural': 'Unprocessed',
                'db_table': 'unprocessed',
            },
        ),
    ]
